// Generated by CoffeeScript 1.3.3
(function() {
  var MessengerBase;

  MessengerBase = (function() {

    function MessengerBase() {
      this.savedBuffer = '';
    }

    MessengerBase.prototype.getHostByAddress = function(address) {
      if (typeof address === 'number') {
        return null;
      }
      if (typeof address === 'string') {
        return address.split(':')[0];
      }
    };

    MessengerBase.prototype.getPortByAddress = function(address) {
      if (typeof address === 'number') {
        return address;
      }
      if (typeof address === 'string') {
        return address.split(':')[1];
      }
    };

    MessengerBase.prototype.prepareJsonToSend = function(json) {
      return JSON.stringify(json) + '\0';
    };

    MessengerBase.prototype.tokenizeData = function(data) {
      var lastToken, tokens;
      data = this.savedBuffer + data;
      tokens = data.toString().split('\0');
      lastToken = tokens.pop();
      if (lastToken) {
        this.savedBuffer += lastToken;
        return [];
      }
      this.savedBuffer = '';
      return tokens;
    };

    return MessengerBase;

  })();

  module.exports = MessengerBase;

}).call(this);
