// Generated by CoffeeScript 1.3.3
var Listener, Speaker,
  __slice = [].slice;

Listener = require('./listener');

Speaker = require('./speaker');

SpeakerPool = require('./speakerPool');

exports.createListener = function (address) {
    return new Listener(address);
};

exports.createSpeaker = function () {
    var addresses;
    addresses = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return new Speaker(addresses);
};

exports.createSpeakerPool = function () {
    var len = arguments.length - 1,
        addresses = [],
        poolSettings;
    for (var arg in arguments) {
        if (+arg && (typeof arguments[arg] === 'object') && +arg === len)
            poolSettings = arguments[arg];
        else
            addresses.push(arguments[arg]);
    }

    return new SpeakerPool(addresses, poolSettings);
}